name: flutter_examples
description: This project contains the Syncfusion Flutter UI widgets examples.
version: 18.1.42
author: Syncfusion <support@syncfusion.com>
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  scoped_model: 1.0.1
  flutter_gallery_assets: 0.1.8
  url_launcher: ^5.0.3
  intl: ^0.16.0
  path_provider: ^1.6.1
  syncfusion_flutter_calendar:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-calendar
      path: flutter_calendar/syncfusion_flutter_calendar
      branch: release/18.1.0.1
  syncfusion_flutter_datepicker:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-datepicker
      path: flutter_datepicker/syncfusion_flutter_datepicker
      branch: release/18.1.0.1
  syncfusion_flutter_charts:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-charts
      path: flutter_charts/syncfusion_flutter_charts
      branch: release/18.1.0.1
  syncfusion_flutter_gauges:
    git: 
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-gauges
      path: flutter_gauges/syncfusion_flutter_gauges
      branch: release/18.1.0.1
  syncfusion_flutter_sliders:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-sliders
      path: flutter_sliders/syncfusion_flutter_sliders
      branch: release/18.1.0.1
  syncfusion_flutter_pdf:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-pdf
      path: flutter_pdf/syncfusion_flutter_pdf
      branch: release/18.1.0.1
  syncfusion_flutter_barcodes:
    git:
      url: https://buildautomation:Coolcomp299@gitlab.syncfusion.com/essential-studio/flutter-barcodes
      path: flutter_barcodes/syncfusion_flutter_barcodes
      branch: release/18.1.0.1


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pdf/
    - lib/sample_details.json
  fonts:
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
